import { NextApiRequest, NextApiResponse } from 'next';

// Hardcoded agent data for better performance
const hardcodedAgents = [
  {
    id: 1,
    name: 'Nina',
    useCaseName: 'Real Estate Lead Qualification',
    industry: 'Real Estate',
    language: 'English (US)',
    function: 'Lead Qualification',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Nina.mp3',
    avatarUrl: null,
    transcript: 'Hi there! I\'m Nina, your real estate assistant at GoZupees. I\'m here to help you navigate the home buying or selling process - whether you\'re a first-time buyer or looking to upgrade. If you have questions about pricing, neighborhoods, or next steps - I\'ve got you covered. Let\'s find the right place for you.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 2,
    name: 'Raj',
    useCaseName: 'Appointment Booking',
    industry: 'Dental Clinic',
    language: 'English (IN)',
    function: 'Appointment Booking',
    country: '🇮🇳 India',
    audioUrl: '/audio/Raj.mp3',
    avatarUrl: null,
    transcript: 'Hi there! I\'m Raj, your appointment assistant here at GoZupees Dental Clinic. I\'m here to help you book, reschedule, or cancel your dental appointments - quickly and easily. Whether it\'s a routine cleaning, a consultation, or an urgent visit, I\'ll make sure you\'re scheduled at the right time with the right doctor. Let\'s get started!',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 3,
    name: 'Jake',
    useCaseName: 'Trial Conversion',
    industry: 'SaaS',
    language: 'English (US)',
    function: 'Trial Conversion',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Jake.mp3',
    avatarUrl: null,
    transcript: 'Hey there! I\'m Jake, your sales assistant at GoZupees. I\'m here to help you make the most of your trial - whether that means walking you through key features, answering any upgrade questions, or showing you how our platform fits your goals. If you\'re finding value already, let\'s explore the best plan to keep things rolling.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 4,
    name: 'Carlos',
    useCaseName: 'Order Support',
    industry: 'E-commerce',
    language: 'English (Latino)',
    function: 'Order Support',
    country: '🇲🇽 Mexico',
    audioUrl: '/audio/carlos_ordersupport.mp3',
    avatarUrl: null,
    transcript: 'Hi! I\'m Carlos, your order support assistant at GoZupees. I can help you track your delivery, update your shipping info, handle returns, or answer any questions about your purchase. If something\'s not right, I\'ll make sure we get it sorted quickly. How can I assist you today?',
    duration: 16,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 5,
    name: 'Zara',
    useCaseName: 'Outbound Sales',
    industry: 'B2B SaaS',
    language: 'English (African)',
    function: 'Outbound Sales',
    country: '🇳🇬 Nigeria',
    audioUrl: '/audio/zara_outboundsales.mp3',
    avatarUrl: null,
    transcript: "Hello! I'm Zara, your sales assistant from GoZupees. I reach out to help businesses like yours discover how our platform can streamline operations and drive results. I'd love to learn more about what you're working on and see how we can support your goals. Let me know if you're open to a quick chat!",
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 6,
    name: 'Pam',
    useCaseName: 'Job Screening',
    industry: 'Recruitment',
    language: 'English (UK)',
    function: 'Job Screening',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Pam.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Pam, your screening assistant at GoZupees. I\'ll be guiding you through a few quick questions to help us understand if this role\'s a good fit for you. Nothing too formal - just a simple way to get to know you better before we move forward. Shall we begin?',
    duration: 14,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 7,
    name: 'Klaus',
    useCaseName: 'Booking Assistant',
    industry: 'Wellness',
    language: 'English (UK)',
    function: 'Booking Assistant',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Klaus.mp3',
    avatarUrl: null,
    transcript: 'Hello there, I\'m Klaus - your booking assistant at GoZupees Wellness. I\'m here to help you schedule your next session, whether it\'s a massage, therapy, or a well-deserved self-care treatment. Just let me know what you\'re looking for, and I\'ll take care of the rest. Shall we get started?',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 8,
    name: 'Chloe',
    useCaseName: 'Dental Receptionist',
    industry: 'Healthcare',
    language: 'English (US)',
    function: 'Dental Reception',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Chloe.mp3',
    avatarUrl: null,
    transcript: 'Hi! I\'m Chloe, your dental receptionist at GoZupees Dental Practice. I\'m here to help you schedule appointments, answer questions about procedures, and assist with insurance inquiries. Whether you need a routine cleaning or have a dental emergency, I\'ll make sure you get the care you need quickly and efficiently.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 9,
    name: 'Robin',
    useCaseName: 'GP Triage',
    industry: 'Healthcare',
    language: 'English (UK)',
    function: 'Medical Triage',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Robin.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Robin, your GP triage assistant at GoZupees Medical Centre. I\'m here to assess your symptoms and determine the most appropriate level of care you need. I can help prioritize urgent cases, provide initial medical guidance, and ensure you receive the right treatment at the right time.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 10,
    name: 'Dean',
    useCaseName: 'Vet Booking (Speciality)',
    industry: 'Healthcare',
    language: 'English (AU)',
    function: 'Veterinary Specialist Booking',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Dean.mp3',
    avatarUrl: null,
    transcript: 'G\'day! I\'m Dean, your veterinary specialist booking assistant at GoZupees Animal Hospital. I help coordinate appointments with our specialized vets for complex cases - whether it\'s cardiology, oncology, or orthopedics. I\'ll make sure your pet gets the expert care they need with minimal wait time.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 11,
    name: 'Hope',
    useCaseName: 'Appointment Reminder (Outbound)',
    industry: 'Healthcare',
    language: 'English (CA)',
    function: 'Outbound Appointment Reminders',
    country: '🇨🇦 Canada',
    audioUrl: '/audio/Hope.mp3',
    avatarUrl: null,
    transcript: 'Hi there! I\'m Hope from GoZupees Healthcare. I\'m calling to remind you about your upcoming appointment tomorrow at 2:30 PM with Dr. Smith. Please confirm if you\'re still able to attend, or let me know if you need to reschedule. We also have some pre-appointment instructions to share with you.',
    duration: 17,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 12,
    name: 'Josh',
    useCaseName: 'Data Collection',
    industry: 'Financial Services',
    language: 'English (US)',
    function: 'Financial Data Collection',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Josh.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Josh, your data collection specialist at GoZupees Financial. I\'m here to help gather your financial information securely and efficiently. I\'ll guide you through our compliance process and ensure all your data is collected accurately for your financial planning needs.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 13,
    name: 'Cooper',
    useCaseName: 'Outbound Mortgage Lead Qualification',
    industry: 'Mortgage Brokerage',
    language: 'English (UK)',
    function: 'Mortgage Lead Qualification',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Cooper.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Cooper, your outbound assistant from Better Mortgages. I\'m calling about your mortgage advice enquiry. I help qualify serious mortgage seekers and book appointments with our expert advisers. I\'ll assess your intent, ability, credit, property needs, and engagement level. Not to brag, but I do love a tidy schedule. Let\'s see how we can help with your mortgage journey.',
    duration: 25,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 14,
    name: 'Archer',
    useCaseName: 'Appointment Reminder (Outbound)',
    industry: 'Financial Services',
    language: 'English (AU)',
    function: 'Financial Appointment Reminders',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Archer.mp3',
    avatarUrl: null,
    transcript: 'Hi there! I\'m Archer from GoZupees Financial Services. I\'m calling to remind you about your financial consultation scheduled for tomorrow at 3:00 PM with our advisor. Please bring your recent statements and ID. If you need to reschedule, just let me know and I\'ll arrange a new time.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 15,
    name: 'Willow',
    useCaseName: 'Lead Qualification (Outbound)',
    industry: 'Financial Services',
    language: 'English (US)',
    function: 'Financial Lead Qualification',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Willow.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Willow from GoZupees Financial. I\'m reaching out because you\'ve shown interest in our wealth management services. I\'d love to learn more about your financial goals and see how our team can help you achieve them. Do you have a few minutes to discuss your investment objectives?',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 16,
    name: 'Zeno',
    useCaseName: 'Generator Sales Specialist - B2B',
    industry: 'eCommerce',
    language: 'English (US)',
    function: 'Generator Sales Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Zeno.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Zeno, your generator specialist at GoZupees Power Solutions. I help businesses and homeowners find the perfect generator for their needs. Tell me about your building size, preferred fuel type, and budget requirements, and I\'ll recommend the ideal generator solution - from small portable units to large commercial systems.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 17,
    name: 'Coco',
    useCaseName: 'Baby Clothing Specialist - DTC',
    industry: 'eCommerce',
    language: 'English (US)',
    function: 'Baby Clothing Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Coco.mp3',
    avatarUrl: null,
    transcript: 'Aloha! I\'m Coco, your baby clothing specialist from Coco Moon Hawaii. I help parents find the perfect soft, organic clothing for their little ones. Whether you need onesies, sleepers, or adorable outfits, I\'ll guide you through our beautiful Hawaiian-inspired collection to find exactly what your baby needs!',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 18,
    name: 'Holly',
    useCaseName: 'Order & Product Support',
    industry: 'eCommerce',
    language: 'English (UK)',
    function: 'Order & Product Support Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Holly.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Holly, your support specialist at GoZupees Health & Home. I help with order tracking, delivery updates, and product usage questions - especially for home health devices. Whether you need help setting up your blood pressure monitor or understanding your pulse oximeter readings, I\'m here to help!',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 19,
    name: 'Max',
    useCaseName: 'Sales Agent',
    industry: 'Automobile Industry',
    language: 'English (US)',
    function: 'Automotive Sales Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Max.mp3',
    avatarUrl: null,
    transcript: 'Hey! I\'m Max from GoZupees Motors. Looking for a new ride? I get it - buying a car is a big decision. I\'ll help you navigate everything from safety ratings and fuel economy to financing options and trade-in values. Whether you need a reliable family car or something sportier, let\'s find what works for your life and budget.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 20,
    name: 'Oliver',
    useCaseName: 'Auto Finance Inquiry',
    industry: 'Automobile Industry',
    language: 'English (CA)',
    function: 'Auto Finance Specialist',
    country: '🇨🇦 Canada',
    audioUrl: '/audio/Oliver.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Oliver from GoZupees Auto Finance. Car financing doesn\'t have to be confusing or stressful. I\'ll walk you through your options - whether you want to buy, lease, or refinance. I can check rates from multiple lenders, explain the fine print, and get you pre-approved so you can shop with confidence.',
    duration: 22,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 21,
    name: 'Anna',
    useCaseName: 'Retail B2C Internet Support',
    industry: 'Telecommunications',
    language: 'English (UK)',
    function: 'Residential Internet Support',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Anna.mp3',
    avatarUrl: null,
    transcript: 'Hi! I\'m Anna from GoZupees Internet Support. Having trouble with your internet connection? I\'m here to help diagnose the issue and get you back online quickly. Whether it\'s a new installation, slow speeds, or complete outage, I\'ll walk you through troubleshooting steps or arrange an engineer visit if needed.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 22,
    name: 'George',
    useCaseName: 'Engineer Appointments',
    industry: 'Telecommunications',
    language: 'English (UK)',
    function: 'Field Engineer Scheduling',
    country: '🇬🇧 UK',
    audioUrl: '/audio/George.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m George from GoZupees Field Services. I coordinate engineer visits for fiber installations and infrastructure work. I\'ll schedule your site survey, arrange access permissions, and ensure our team has everything needed for a successful installation. Let me get your appointment booked.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 23,
    name: 'Mark',
    useCaseName: 'Wholesale Order Support',
    industry: 'Telecommunications',
    language: 'English (UK)',
    function: 'Wholesale Order Management',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Mark.mp3',
    avatarUrl: null,
    transcript: 'Hi, this is Mark from GoZupees Wholesale Division. I handle order tracking and support for our channel partners. Whether you need updates on leased line installations, service modifications, or billing queries, I have access to all your wholesale orders and can provide real-time status updates.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 24,
    name: 'Jane',
    useCaseName: 'Complaint & Triage (Traffic Lights)',
    industry: 'Telecommunications',
    language: 'English (UK)',
    function: 'Emergency Network Support',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Jane.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Jane from GoZupees Emergency Network Support. If you\'re experiencing issues with traffic lights or critical infrastructure, I\'ll log your report immediately and dispatch our emergency response team. I can provide incident reference numbers and estimated repair times.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 25,
    name: 'Eliza',
    useCaseName: 'Technical Testing (On call)',
    industry: 'Telecommunications',
    language: 'English (UK)',
    function: 'Line Testing Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Eliza.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Eliza from GoZupees Technical Testing. I can run live diagnostics on your internet connection to identify faults, check line quality, and measure performance metrics. Whether you\'re a field engineer or customer, I\'ll provide detailed test results and recommend next steps.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 26,
    name: 'Andrew',
    useCaseName: 'Internet Complaint Triage to ISP Support',
    industry: 'Telecommunications',
    language: 'English (UK)',
    function: 'Support Routing Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Andrew.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Andrew from GoZupees Support Routing. I help direct your call to the right team - whether that\'s your ISP, Openreach, or our technical department. I\'ll gather your details and ensure you reach the specialist who can actually resolve your specific internet issue.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 27,
    name: 'Hailee',
    useCaseName: 'Appointment Reminder (Outbound)',
    industry: 'Telecommunications',
    language: 'English (US)',
    function: 'Appointment Coordination',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Hailee.mp3',
    avatarUrl: null,
    transcript: 'Hi, this is Hailee from GoZupees Field Services. I\'m calling to confirm your engineer appointment for tomorrow between 1-5 PM. Our technician will need access to your property and may require up to 3 hours for the fiber installation. Please confirm if this time still works for you.',
    duration: 17,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 28,
    name: 'Adam',
    useCaseName: 'Lead Qualification Outbound',
    industry: 'Telecommunications',
    language: 'English (UK)',
    function: 'Broadband Sales Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Adam.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Adam from GoZupees Broadband. You recently inquired about our internet services. I\'d like to discuss your requirements - how many devices you have, your usage patterns, and whether you need business-grade connectivity. This helps me recommend the perfect package and installation timeline.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 29,
    name: 'Joshua',
    useCaseName: 'Application Support',
    industry: 'Mortgage Brokers',
    language: 'English (US)',
    function: 'Mortgage Application Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Joshua.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Joshua from GoZupees Mortgage Solutions. I help clients navigate the mortgage application process step by step. Whether you need help with documentation, understanding requirements, or tracking your application status, I\'ll make sure everything moves smoothly toward your home loan approval.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 30,
    name: 'Emily',
    useCaseName: 'Pre-Sale Information Provider',
    industry: 'Mortgage Brokers',
    language: 'English (UK)',
    function: 'Mortgage Information Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Emily.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Emily from GoZupees Mortgage Advisors. I provide detailed information about our mortgage products, interest rates, and qualification requirements. Whether you\'re a first-time buyer or looking to remortgage, I\'ll help you understand your options and find the right mortgage solution.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 31,
    name: 'Lima',
    useCaseName: 'Loan Inquiry Assistants',
    industry: 'Mortgage Brokers',
    language: 'English (US)',
    function: 'Loan Analysis Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Lima.mp3',
    avatarUrl: null,
    transcript: 'Hi there! I\'m Lima from GoZupees Lending. I specialize in analyzing loan options and comparing interest rates from multiple lenders. I\'ll help you understand different loan products, calculate potential payments, and find the most competitive rates that match your financial situation.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 32,
    name: 'Jenny',
    useCaseName: 'EMI Reminder (Outbound)',
    industry: 'Mortgage Brokers',
    language: 'English (IN)',
    function: 'Payment Reminder Specialist',
    country: '🇮🇳 India',
    audioUrl: '/audio/Jenny.mp3',
    avatarUrl: null,
    transcript: 'Hello, this is Jenny from GoZupees Mortgage Services. I\'m calling to remind you about your upcoming EMI payment due on the 15th. I can help you set up automatic payments, discuss payment options if you\'re facing difficulties, or answer any questions about your mortgage account.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 33,
    name: 'Cooper',
    useCaseName: 'Lead Qualification (Outbound)',
    industry: 'Mortgage Brokers',
    language: 'English (AU)',
    function: 'Mortgage Lead Specialist',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Cooper.mp3',
    avatarUrl: null,
    transcript: 'G\'day! I\'m Cooper from GoZupees Home Loans. You recently showed interest in our mortgage services. I\'d like to chat about your home buying plans, assess your borrowing capacity, and see how we can help make your property dreams a reality. When would be a good time to discuss your requirements?',
    duration: 22,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 34,
    name: 'Noah',
    useCaseName: 'Application Support',
    industry: 'Insurance Brokers',
    language: 'English (US)',
    function: 'Insurance Application Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Noah.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Noah from GoZupees Insurance Services. I help clients complete their insurance applications smoothly and efficiently. Whether you need help with health questionnaires, documentation requirements, or understanding coverage options, I\'ll guide you through every step of the application process.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 35,
    name: 'Ivy',
    useCaseName: 'Pre-Sale Information Provider',
    industry: 'Insurance Brokers',
    language: 'English (UK)',
    function: 'Insurance Information Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Ivy.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Ivy from GoZupees Insurance Advisors. I provide comprehensive information about our insurance products, coverage options, and policy benefits. Whether you\'re looking for life, health, home, or business insurance, I\'ll help you understand what\'s available and find the right protection for your needs.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 36,
    name: 'Lily',
    useCaseName: 'Policy Inquiry Assistants',
    industry: 'Insurance Brokers',
    language: 'English (CA)',
    function: 'Policy Information Specialist',
    country: '🇨🇦 Canada',
    audioUrl: '/audio/Lily.mp3',
    avatarUrl: null,
    transcript: 'Hi there! I\'m Lily from GoZupees Insurance Support. I help policyholders understand their coverage, explain benefits, answer questions about claims procedures, and clarify policy terms. Whether you\'re reviewing your existing coverage or have questions about what\'s included, I\'m here to help.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 37,
    name: 'Luke',
    useCaseName: 'Premium Payment Reminder (Outbound)',
    industry: 'Insurance Brokers',
    language: 'English (US)',
    function: 'Payment Reminder Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Luke.mp3',
    avatarUrl: null,
    transcript: 'Hello, this is Luke from GoZupees Insurance. I\'m calling to remind you that your insurance premium payment is due soon. I can help you set up automatic payments, discuss payment options, or answer any questions about your policy renewal. Let\'s make sure your coverage continues without interruption.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 38,
    name: 'Josie',
    useCaseName: 'Lead Qualification (Outbound)',
    industry: 'Insurance Brokers',
    language: 'English (AU)',
    function: 'Insurance Lead Specialist',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Josie.mp3',
    avatarUrl: null,
    transcript: 'G\'day! I\'m Josie from GoZupees Insurance Solutions. You recently inquired about our insurance services. I\'d love to discuss your coverage needs, assess your current situation, and see how we can provide better protection for you and your family. When would be a convenient time to chat?',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 39,
    name: 'Freya',
    useCaseName: 'Receptionist',
    industry: 'Law Firms',
    language: 'English (UK)',
    function: 'Legal Receptionist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Freya.mp3',
    avatarUrl: null,
    transcript: 'Good morning, GoZupees Legal Services, this is Freya speaking. How may I assist you today? Whether you need to schedule a consultation, speak with one of our attorneys, or have questions about your case, I\'m here to help connect you with the right person.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 40,
    name: 'Jack',
    useCaseName: 'Client Onboarding',
    industry: 'Law Firms',
    language: 'English (US)',
    function: 'Legal Client Intake Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Jack.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Jack from GoZupees Legal. I\'ll be helping you get started as a new client. I\'ll guide you through our intake process, help you gather necessary documents, and explain our legal procedures. This ensures our attorneys have everything they need to represent you effectively.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 41,
    name: 'Isla',
    useCaseName: 'Court Date Reminder (Outbound)',
    industry: 'Law Firms',
    language: 'English (UK)',
    function: 'Legal Appointment Coordinator',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Isla.mp3',
    avatarUrl: null,
    transcript: 'Hello, this is Isla from GoZupees Legal. I\'m calling to remind you about your court appearance scheduled for next Tuesday at 10 AM. Please arrive 30 minutes early and bring the documents we discussed. If you have any questions or need to reschedule, please let me know immediately.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 42,
    name: 'Anna',
    useCaseName: 'Receptionist',
    industry: 'Accounting Firms',
    language: 'English (US)',
    function: 'Accounting Receptionist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Anna_Accounting.mp3',
    avatarUrl: null,
    transcript: 'Thank you for calling GoZupees Accounting, this is Anna. How can I help you today? Whether you need to schedule a consultation, discuss tax services, or speak with one of our CPAs, I\'ll make sure you get connected with the right person for your accounting needs.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 43,
    name: 'Mia',
    useCaseName: 'Client Onboarding',
    industry: 'Accounting Firms',
    language: 'English (AU)',
    function: 'Accounting Client Setup Specialist',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Mia.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Mia from GoZupees Accounting. I\'ll help you get set up as a new client and gather all the information our accountants need. This includes your financial documents, business structure details, and accounting preferences to ensure we provide the best service for your needs.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 44,
    name: 'Ava',
    useCaseName: 'Tax Date Notifications Reminder (Outbound)',
    industry: 'Accounting Firms',
    language: 'English (CA)',
    function: 'Tax Deadline Coordinator',
    country: '🇨🇦 Canada',
    audioUrl: '/audio/Ava.mp3',
    avatarUrl: null,
    transcript: 'Hello, this is Ava from GoZupees Accounting. I\'m calling to remind you that your tax filing deadline is approaching on April 30th. We still need your T4 slips and expense receipts to complete your return. Please submit these documents by next Friday to avoid any delays.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 45,
    name: 'Theo',
    useCaseName: 'Employer Assistant',
    industry: 'Recruitment Agencies',
    language: 'English (UK)',
    function: 'Employer Services Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Theo.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Theo from GoZupees Recruitment. I help companies find the perfect candidates for their open positions. I can assist with job posting requirements, candidate screening criteria, interview scheduling, and provide market insights to ensure you attract top talent.',
    duration: 22,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 46,
    name: 'Archie',
    useCaseName: 'Jobseeker Assistant',
    industry: 'Recruitment Agencies',
    language: 'English (AU)',
    function: 'Career Guidance Specialist',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Archie.mp3',
    avatarUrl: null,
    transcript: 'G\'day! I\'m Archie from GoZupees Career Services. I help job seekers find their ideal positions and advance their careers. Whether you need help with your CV, interview preparation, or finding roles that match your skills and goals, I\'m here to support your job search journey.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 47,
    name: 'Leo',
    useCaseName: 'New Job Alert (Outbound)',
    industry: 'Recruitment Agencies',
    language: 'English (US)',
    function: 'Job Opportunity Coordinator',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Leo.mp3',
    avatarUrl: null,
    transcript: 'Hi, this is Leo from GoZupees Recruitment. I\'m calling about an exciting new opportunity that matches your profile - a senior marketing manager position with excellent benefits and growth potential. Are you available for a quick chat about this role?',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 48,
    name: 'Fred',
    useCaseName: 'New Job Setup (Incoming)',
    industry: 'Recruitment Agencies',
    language: 'English (UK)',
    function: 'Job Intake Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Fred.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Fred from GoZupees Recruitment. I understand you have a new position to fill. I\'ll help gather all the details - job requirements, salary range, company culture, and ideal candidate profile. This ensures we find the perfect match for your team.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 49,
    name: 'Sienna',
    useCaseName: 'Receptionist',
    industry: 'Education Providers',
    language: 'English (US)',
    function: 'Educational Institution Receptionist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Sienna.mp3',
    avatarUrl: null,
    transcript: 'Good morning, GoZupees Academy, this is Sienna. How may I help you today? Whether you\'re inquiring about enrollment, need to speak with a teacher, or have questions about our programs, I\'ll make sure you get the information and assistance you need.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 50,
    name: 'Oscar',
    useCaseName: 'Admissions Support Assistant',
    industry: 'Education Providers',
    language: 'English (UK)',
    function: 'Admissions Coordinator',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Oscar.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Oscar from GoZupees Academy Admissions. I\'m here to guide you through our application process, explain program requirements, help with documentation, and answer any questions about enrollment. Let\'s get you started on your educational journey.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 51,
    name: 'Isabella',
    useCaseName: 'Student Support Hotline',
    industry: 'Education Providers',
    language: 'English (CA)',
    function: 'Student Services Specialist',
    country: '🇨🇦 Canada',
    audioUrl: '/audio/Isabella.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Isabella from GoZupees Student Support. I\'m here to help with any academic or administrative questions you might have. Whether it\'s course scheduling, academic resources, or student services, I\'ll make sure you get the support you need to succeed.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 52,
    name: 'Sofia',
    useCaseName: 'Inquiry Assistance',
    industry: 'Real Estate Agencies',
    language: 'English (US)',
    function: 'Property Inquiry Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Sofia.mp3',
    avatarUrl: null,
    transcript: 'Hello! I\'m Sofia from GoZupees Real Estate. I can help you with information about any of our properties, neighborhood details, pricing, and next steps. Whether you\'re buying, selling, or just exploring options, I\'m here to make your real estate journey smooth and successful.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 53,
    name: 'Alfie',
    useCaseName: 'Lead Qualification',
    industry: 'Real Estate Agencies',
    language: 'English (UK)',
    function: 'Real Estate Lead Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Alfie.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Alfie from GoZupees Property. I understand you\'re interested in buying or selling property. I\'d like to learn more about your requirements, timeline, and budget to ensure we match you with the perfect properties and provide the best service possible.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 54,
    name: 'Harper',
    useCaseName: 'New Property Alert',
    industry: 'Real Estate Agencies',
    language: 'English (AU)',
    function: 'Property Alert Coordinator',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Harper.mp3',
    avatarUrl: null,
    transcript: 'Hi, this is Harper from GoZupees Real Estate. I\'m calling about a new property that just came on the market that matches your search criteria - a 3-bedroom home in your preferred area within your budget. Would you like to schedule a viewing this weekend?',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 55,
    name: 'James',
    useCaseName: 'Viewing Booking & Rescheduling',
    industry: 'Real Estate Agencies',
    language: 'English (CA)',
    function: 'Property Viewing Coordinator',
    country: '🇨🇦 Canada',
    audioUrl: '/audio/James.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m James from GoZupees Real Estate. I coordinate property viewings and can help you schedule, reschedule, or get directions to any property showing. I\'ll make sure you have all the details you need and that the timing works perfectly for everyone involved.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 56,
    name: 'David',
    useCaseName: 'ISP Technical Support',
    industry: 'ISPs & MSPs',
    language: 'English (US)',
    function: 'Internet Technical Support Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/David.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m David from GoZupees Internet Services. I handle technical support for internet connectivity issues, router troubleshooting, and network optimization. Whether you\'re experiencing slow speeds, connection drops, or need help setting up your equipment, I\'ll get you back online quickly.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 57,
    name: 'Maggie',
    useCaseName: 'MSP Customer Onboarding',
    industry: 'ISPs & MSPs',
    language: 'English (UK)',
    function: 'Managed Services Onboarding Specialist',
    country: '🇬🇧 UK',
    audioUrl: '/audio/Maggie.mp3',
    avatarUrl: null,
    transcript: 'Hello, I\'m Maggie from GoZupees Managed Services. I help new clients get started with our IT support services, including account setup, service agreement details, and initial system assessments. I\'ll ensure a smooth transition to our managed IT services.',
    duration: 19,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 58,
    name: 'Soniya',
    useCaseName: 'ISP Billing Support',
    industry: 'ISPs & MSPs',
    language: 'English (IN)',
    function: 'Internet Billing Support Specialist',
    country: '🇮🇳 India',
    audioUrl: '/audio/Soniya.mp3',
    avatarUrl: null,
    transcript: 'Hi, I\'m Soniya from GoZupees Internet Billing. I help customers with billing inquiries, payment processing, plan upgrades, and account management. Whether you need to update your payment method or understand your bill, I\'m here to assist you.',
    duration: 18,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 59,
    name: 'Jake',
    useCaseName: 'MSP Help Desk',
    industry: 'ISPs & MSPs',
    language: 'English (US)',
    function: 'IT Help Desk Specialist',
    country: '🇺🇸 USA',
    audioUrl: '/audio/Jake_MSP.mp3',
    avatarUrl: null,
    transcript: 'Hey, I\'m Jake from GoZupees IT Support. I handle help desk tickets for businesses using our managed services. From software issues to hardware problems, network troubleshooting to user support, I\'ll diagnose and resolve your IT challenges efficiently.',
    duration: 21,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  },
  {
    id: 60,
    name: 'Mary',
    useCaseName: 'ISP Sales & Upgrades',
    industry: 'ISPs & MSPs',
    language: 'English (AU)',
    function: 'Internet Sales Specialist',
    country: '🇦🇺 Australia',
    audioUrl: '/audio/Mary.mp3',
    avatarUrl: null,
    transcript: 'G\'day, I\'m Mary from GoZupees Internet Sales. I help customers find the right internet plan for their needs and assist with service upgrades. Whether you need faster speeds, business connectivity, or bundled services, I\'ll find the perfect package for you.',
    duration: 20,
    createdAt: new Date('2025-05-28T10:18:59.976Z')
  }
];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  try {
    console.log('Returning hardcoded agents data:', hardcodedAgents.length, 'agents');
    res.status(200).json(hardcodedAgents);
  } catch (error) {
    console.error('Error returning demos:', error);
    res.status(500).json({
      success: false,
      message: 'Internal server error',
    });
  }
}